language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_install:  
  - composer install --dev --no-interaction --prefer-source

after_script:
  - php vendor/bin/coveralls

notifications:
  email: "demateus@gmail.com"